### ISSUE TITLE
does not seems to work...

### ISSUE THREAD

**Issue by lmnogues** [arcsector/vscode-splunk-search-linter#2]
I've installed the extension and i've not coloration on my .spl/.splunk files

AS if it was not really enabled or only partially installed
there is not language mode associated with the .spl/.splunk files

```
Name: Splunk Search Autocompletion Tool
Id: arcsector.vscode-splunk-search-linter
Description: Splunk Search suggestions for Splunk SPL Files
Version: 0.1.2
Publisher: arcsector
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=arcsector.vscode-splunk-search-linter
```

**Comment by arcsector** [comment]
It isn't associated with any languages because VSC Marketplace only assumes language mode when a language is contributed; this might be fixed by merging the linter and the syntax highlighter together, since the highlighter provides the language definition code, which the linter then uses for activation:

```typescript
let splunkSelector:vscode.DocumentSelector = {
	scheme: 'file',
	language: 'splunk'
};
```

Then all providers are initialized with the document selector on the `splunk` language ID.

Let me know what you think, or if this issue is fixed after installing the syntax highlighter.

**Comment by arcsector** [comment]
Made sure this doesn't happen again by specifying that the syntax is necessary in [README](/arcsector/vscode-splunk-search-linter/blob/master/README.md) at 6ad9840, and by adding extension dependency in 76609e3.
